/** Shared by page parallax and the Pixi renderer. Colors mirror design-tokens.css. */
export const palette = {
  void: '#020107',
  ink: '#0e0930',
  night: '#231757',
  dusk: '#36287d',
  violet: '#4835ab',
  ultraviolet: '#6449d7',
  haze: '#9287b8',
  mist: '#b1b7d0',
  ice: '#aef7fc',
  signal: '#1ed3f0',
  glow: '#d4526d',
  glowDeep: '#b14766',
} as const;
export const bluePalette = {
  void: '#030c18',
  ink: '#07172b',
  night: '#102b49',
  dusk: '#234b73',
  violet: '#295a93',
  ultraviolet: '#548ac7',
  haze: '#9aaccc',
  mist: '#cedbe8',
  ice: '#b9f0ff',
  signal: '#58d1ee',
  glow: '#f092a4',
  glowDeep: '#b14766',
} as const;
export const paletteForTheme = (theme: string | undefined) =>
  theme === 'blue' ? bluePalette : palette;
export const visualConfig = {
  palette,
  filters: {
    enabled: true,
    crt: {
      curvature: 0,
      lineWidth: 1,
      lineContrast: 0.08,
      noise: 0,
      vignetting: 0.15,
      vignettingAlpha: 0.18,
      vignettingBlur: 0.5,
      seed: 0.5,
    },
    noise: { noise: 0.08, seed: 0.5 },
    noiseOpacity: 0.16,
    bloom: {
      threshold: 0.8,
      bloomScale: 0.18,
      brightness: 1,
      blur: 3,
      quality: 2,
    },
    rgb: { red: { x: 1, y: 0 }, green: { x: 0, y: 0 }, blue: { x: -1, y: 0 } },
    dealBlur: { velocity: { x: 2, y: 0 }, kernelSize: 5, offset: 0 },
  },
  performance: {
    maxResolution: 1.5,
    maxFPS: 60,
    frameBudgetMs: 20,
    slowDurationMs: 2000,
    sampleWindowMs: 250,
    warmupMs: 1500,
  },
  motion: {
    lerp: 0.08,
    minimumScrollWidth: 768,
    settleEpsilon: 0.02,
    heroPhoto: { speed: 0.3, pointer: 12 },
    heroLights: { speed: 0.6, pointer: 6 },
    heroTitle: { speed: 1, pointer: 0 },
    heroCards: {
      count: 3,
      durationMinMs: 7000,
      durationSpreadMs: 4000,
      gapMaxMs: 3000,
      columns: [15, 40, 65],
      horizontalSpread: 12,
      topMin: 24,
      verticalSpread: 27,
    },
    tunnel: { speed: 0.2, pointer: 0 },
    table: { lights: 10, surface: 4, cards: 0 },
    deal: { durationMs: 450, slidePx: 18, liftPx: 5 },
    flicker: { amount: 0.03, intervalMinMs: 2600, intervalMaxMs: 5200 },
  },
};
export const assetUrl = (path: string) => `${import.meta.env.BASE_URL}${path}`;
