<script lang="ts">
  import { orderedLabels } from '../../content/facts';

  let {
    size = 3,
    take = 2,
  }: {
    size?: number;
    take?: number;
  } = $props();
  let paths = $derived(orderedLabels(size, take));
</script>

<div class="counting-example">
  <p>
    {paths.length} ordered paths, generated by taking a different remaining card at
    each branch:
  </p>
  <ul class="order-paths">
    {#each paths as p (p.join(''))}<li>{p.join(' → ')}</li>{/each}
  </ul>
</div>
